### ISSUE TITLE
GNOME 42 theme isn't recognized as valid

### ISSUE THREAD

**Issue by salperinlea** [Fausto-Korpsvart/Tokyo-Night-GTK-Theme#10]
When one downloads the gnome 42 variant of the theme and attempts to install it, it isn't recognized as a valid theme by tweaks. What should be done for this version?

**Comment by Fausto-Korpsvart** [comment]
> When one downloads the gnome 42 variant of the theme and attempts to install it, it isn't recognized as a valid theme by tweaks. What should be done for this version?

Hi, @salperinlea, The variant for Gnome 42 is not recognized by Tweaks, the Gnome 42 file must be placed in the following path: '.config/gtk-4.0/' with the name 'gtk.css', this makes it automatically recognized for gtk4/libadwaita applications; the normal versions, not Gnome 42, must be placed in the path: '. themes', those are recognized by Tweaks, and these are for gtk3 applications, that is to say, you must download both versions and place them in the paths I already mentioned so that they work with both applications, gtk3, gtk4/libadwaita and the theme is uniform.

Thanks for reporting, this makes me think that I should update the description to make it a bit clearer about the use of each version. };-]

**Comment by 0Aredjay0** [comment]
I did what you said but all of my windows are still the gnome colors.  the gtk.css thing does nothing at all
