### ISSUE TITLE
[Icon request] Librewolf icon request.

### ISSUE THREAD

**Issue by AlvaroParker** [Fausto-Korpsvart/Tokyo-Night-GTK-Theme#15]
Hi, I love this theme specially the icon theme but I notice there is no icon for [Librewolf](https://librewolf.net/). Will it be possible for you to add one?

**Comment by Fausto-Korpsvart** [comment]
> 

Greetings, @AlvaroParker, thanks for your support, it's great that you like the theme.

Well, regarding your request, unfortunately I'm not an expert in creating icon themes, and I can't promise anything either, but I can research how to do it and if I find a way to add new icons I will do it, because I also have icons that I would like to be in the package, if I find a way and I manage to add new icons, I will do an update and you will see the Librewolf icon.

Thanks again for your support.
