### ISSUE TITLE
pop os testing - seems to use light mode for dark theme

### ISSUE THREAD

**Issue by ryannathans** [Fausto-Korpsvart/Tokyo-Night-GTK-Theme#17]
my apps like element or geary are using a very bright white theme instead of a dark theme when the borderless dark theme is applied in gnome 42/pop os 22.04

when i use "pop-dark" for legacy applications in gnome tweaks, the issue is gone but then most apps aren't themed

**Comment by Fausto-Korpsvart** [comment]
> 



> my apps like element or geary are using a very bright white theme instead of a dark theme when the borderless dark theme is applied in gnome 42/pop os 22.04
> 
> when i use "pop-dark" for legacy applications in gnome tweaks, the issue is gone but then most apps aren't themed

I haven't actually tested PopOS!, I'm going to test to find out what's wrong and fix it as soon as possible.
One more thing, could you post some screenshots to get an idea of the problem?

Thanks for reporting, @ryannathans };-]

**Comment by ryannathans** [comment]
not sure if it matters but they are flatpak apps

this is geary with the theme on
![image](https://user-images.githubusercontent.com/1307375/184520965-45024aac-072b-4973-88a3-80ea4494280a.png)

and this is with pop-dark for legacy apps
![image](https://user-images.githubusercontent.com/1307375/184520993-938b76dd-15b4-4791-a666-5f732075b02a.png)

GNOME Shell 42.3.1

I downloaded 

Tokyonight-Dark-BL.zip | 8.0 | Tokyonight Dark Borderless Version

extracted it in ~./themes

and in gnome tweaks

![image](https://user-images.githubusercontent.com/1307375/184521064-4aac3cce-3ed6-46fe-8f36-9e6e4dc63351.png)

**Comment by Fausto-Korpsvart** [comment]
> not sure if it matters but they are flatpak apps
> 
> this is geary with the theme on ![image](https://user-images.githubusercontent.com/1307375/184520965-45024aac-072b-4973-88a3-80ea4494280a.png)
> 
> and this is with pop-dark for legacy apps ![image](https://user-images.githubusercontent.com/1307375/184520993-938b76dd-15b4-4791-a666-5f732075b02a.png)
> 
> GNOME Shell 42.3.1
> 
> I downloaded
> 
> Tokyonight-Dark-BL.zip | 8.0 | Tokyonight Dark Borderless Version
> 
> extracted it in ~./themes
> 
> and in gnome tweaks
> 
> ![image](https://user-images.githubusercontent.com/1307375/184521064-4aac3cce-3ed6-46fe-8f36-9e6e4dc63351.png)



> not sure if it matters but they are flatpak apps
> 
> this is geary with the theme on ![image](https://user-images.githubusercontent.com/1307375/184520965-45024aac-072b-4973-88a3-80ea4494280a.png)
> 
> and this is with pop-dark for legacy apps ![image](https://user-images.githubusercontent.com/1307375/184520993-938b76dd-15b4-4791-a666-5f732075b02a.png)
> 
> GNOME Shell 42.3.1
> 
> I downloaded
> 
> Tokyonight-Dark-BL.zip | 8.0 | Tokyonight Dark Borderless Version
> 
> extracted it in ~./themes
> 
> and in gnome tweaks
> 
> ![image](https://user-images.githubusercontent.com/1307375/184521064-4aac3cce-3ed6-46fe-8f36-9e6e4dc63351.png)

Yes, it does matter if they are Flatpak applications, here is an article that explains how to run a command in the terminal to apply GTK themes in Flatpak. [Apply GTK themes to Flatpak Apps](https://itsfoss.com/flatpak-app-apply-theme/)

**Comment by ryannathans** [comment]
~$ sudo flatpak override --filesystem=$HOME/.themes
~$ sudo flatpak override --env=GTK_THEME=Tokyonight-Dark-BL
~$ ls ~/.themes
Tokyonight-Dark-BL

then restarting geary, still looks the same - bright white

**Comment by Fausto-Korpsvart** [comment]
> ~$ sudo flatpak override --filesystem=$HOME/.themes ~$ sudo flatpak override --env=GTK_THEME=Tokyonight-Dark-BL ~$ ls ~/.themes Tokyonight-Dark-BL
> 
> then restarting geary/relogging, still looks the same - bright white

OK, I downloaded the PopOS! ISO, I'm going to test to see where the error is because for Flatpak applications that command has always worked for me. 
One more question, have you downloaded the Gnome42 theme?, because if they are GTK4/Libadwaita applications, the theme doesn't apply with GTK3 themes. You could try applying the specific theme for Gnome 42.
Anyway, I'm going to install PopOS! and test to see where the error is.

**Comment by ryannathans** [comment]
I tried the gnome42 theme but it didn't seem to change anything (that I could find anyway) when placed in ~/.config/gtk-4.0/gtk.css

also, not sure if they are supposed to be affected but the dock and application launcher are unaffected by the theme eg
![image](https://user-images.githubusercontent.com/1307375/184522080-d07f35b0-5fc3-4227-8c59-272984d518b5.png)
![image](https://user-images.githubusercontent.com/1307375/184522084-803ee471-0fa1-4919-a2b1-ba1978d4e9eb.png)

appreciate the assistance and testing :)

**Comment by ryannathans** [comment]
![image](https://user-images.githubusercontent.com/1307375/184522159-24ebfc90-b4bb-4c78-9bb6-060b8ef41cfb.png)
also seeing some light themeing in the launcher

**Comment by Fausto-Korpsvart** [comment]
> I tried the gnome42 theme but it didn't seem to change anything (that I could find anyway) when placed in ~/.config/gtk-4.0/gtk.css
> 
> also, not sure if they are supposed to be affected but the dock and application launcher are unaffected by the theme eg ![image](https://user-images.githubusercontent.com/1307375/184522080-d07f35b0-5fc3-4227-8c59-272984d518b5.png) ![image](https://user-images.githubusercontent.com/1307375/184522084-803ee471-0fa1-4919-a2b1-ba1978d4e9eb.png)
> 
> appreciate the assistance and testing :)

Well, I'm going to do the tests to fix these errors as soon as possible.

And no, the white colour in the shell menu is supposed to be like that to make some contrast.

I'll do the tests and when I solve the bugs I'll make the updates.

Thanks for reporting and for your support.

**Comment by Fausto-Korpsvart** [comment]
> > I tried the gnome42 theme but it didn't seem to change anything (that I could find anyway) when placed in ~/.config/gtk-4.0/gtk.css
> > also, not sure if they are supposed to be affected but the dock and application launcher are unaffected by the theme eg ![image](https://user-images.githubusercontent.com/1307375/184522080-d07f35b0-5fc3-4227-8c59-272984d518b5.png) ![image](https://user-images.githubusercontent.com/1307375/184522084-803ee471-0fa1-4919-a2b1-ba1978d4e9eb.png)
> > appreciate the assistance and testing :)
> 
> Well, I'm going to do the tests to fix these errors as soon as possible.
> 
> And no, the white colour in the shell menu is supposed to be like that to make some contrast.
> 
> I'll do the tests and when I solve the bugs I'll make the updates.
> 
> Thanks for reporting and for your support.

I just installed PopOS and Geary is already installed, I installed Element and I don't see any problem with any of those applications. I guess because they are Flatpak applications, the theme is not applied, which indicates that the theme is not the problem.
The only problem I've noticed is that the PopOS Applications Menu doesn't apply the theme and neither does the Dock, for the Dock you can install the Dash To Dock for Cosmic extension from Gnome Extensions to change the appearance.
With the PopOS Application Menu, I'm going to try to make it work.

Again, thanks for reporting and for your support.

![Element](https://user-images.githubusercontent.com/47998118/184523408-0dc66634-f971-4fb5-ae1c-07ba88fe9a6b.png)
![Geary](https://user-images.githubusercontent.com/47998118/184523414-637cdbe9-feed-48b2-9e9d-5def08902aac.png)

**Comment by ryannathans** [comment]
How did you get geary into dark mode whilst using theme? If I set legacy applications in gnome tweaks from pop-dark to Tokyonight-Dark-BL then geary and element turn white

Maybe I am applying the theme wrong somehow

**Comment by Fausto-Korpsvart** [comment]
> How did you get geary into dark mode whilst using theme? If I set legacy applications in gnome tweaks from pop-dark to Tokyonight-Dark-BL then geary and element turn white (element does use the correct top bar though, but in light theme)
> 
> ![image](https://user-images.githubusercontent.com/1307375/184523637-c1bceba2-73b4-4c14-8188-8e59d8c286a5.png)
> 
> Maybe I am applying the theme wrong/partially somehow?

For Geary you must install the Ubuntu (deb) version from the PopOS Shop.
![pop_shop](https://user-images.githubusercontent.com/47998118/184523957-5ecb44ed-e047-40a3-8b9c-fbcf125b1a15.png)

With Element, the theme is only applied to the title bar because the application is probably not made in GTK and so the theme is not applied for that reason.

With the Dock, install the Dash To Dock for Cosmic extension and disable the PopOS Dock from the settings.

**Comment by ryannathans** [comment]
Thanks. Apps seem to think the theme is light and default to light mode. Is there any way to override this? When I use themes with a dark variant like pop-dark they default to dark mode.

**Comment by Fausto-Korpsvart** [comment]
> Thanks. Apps seem to think the theme is light and default to light mode. Is there any way to override this? When I use themes with a dark variant like pop-dark they default to dark mode.

If I remember correctly, I think editing the 'settings.ini' file in '~/.config/gtk3.0' can do it, you should add this line:

[Settings]
gtk-application-prefer-dark-theme=1

If the file does not exist, you can create it, and it should look like this:
![settings.ini](https://user-images.githubusercontent.com/47998118/184524351-c364ba21-8693-4880-ace1-e7b9270739f2.png)
If that doesn't work, then I'll look for a solution and let you know so that I can fix that problem.

**Comment by ryannathans** [comment]
Unfortunately didn't work.

Interestingly, this was set to 0. I set it to 1 and rebooted. Apps such as the flatpak geary still apply the light mode. When I swap to the pop-dark legacy applications theme, geary and element swap to dark mode. I wonder what the pop-dark theme is doing differently to achieve this. I am having a hard time finding gtk3 documentation about creating dark mode themes.

**Comment by ryannathans** [comment]
https://docs.flatpak.org/en/latest/desktop-integration.html?highlight=theme#theming

aha i think flatpaks will copy the system theme - only if there is a flatpak theme with the same name

and because there is one for pop-dark and not for this theme - that is why flatpaks do not inherit the dark mode (or any other styling) from this theme

**Comment by ryannathans** [comment]
https://www.linuxuprising.com/2018/05/how-to-get-flatpak-apps-to-use-correct.html

feel like publishing the theme on flathub? :P

**Comment by Fausto-Korpsvart** [comment]
> 

Thanks for the info, I really have no idea how to publish themes to Flatpak, it always worked for me to run the above command to make themes apply to Fatpak, I will check the documentation to know how to do it and then try to publish a theme as a test to see if they will work because I don't know what changes I need to make to the 'css' files to make it work.

Anyway, I'm going to read the documentation to find out what I need to do and find the solution.

Thanks for the support and for the info. };-]

**Comment by ryannathans** [comment]
thanks dude, enjoying the theme!

**Comment by Fausto-Korpsvart** [comment]
> thanks dude, enjoying the theme!

I have found a way to make themes work in Flatpak applications!!

Just copy the themes to the following path, which I guess is the path where the packaged Flatpak themes are installed, the path is: ~/.local/share/flatpak/org.gnome.Platform/x86_64/41/...
Then there is a folder with a long numeric code and inside that folder there is another folder called 'files' inside files you look for the folder 'share' and inside look for the folder 'themes', the full path would be: ~/.local/share/flatpak/org.gnome.Platform/x86_64/41/the long numeric code folder/files/share/themes

Everything is explained in this article in Linux Mint [Adding Custom Themes to Flatpak Apps](https://forums.linuxmint.com/viewtopic.php?t=284418)

I hope this will help while I look for a way to package the themes for Flatpak.

**Comment by atraxsrc** [comment]
For pop_os i recocmend this script for legacy apps https://github.com/atraxsrc/libadwaita-theme-changer
