### ISSUE TITLE
Missing icon in Location Services

### ISSUE THREAD

**Issue by XMelph** [Fausto-Korpsvart/Tokyo-Night-GTK-Theme#21]
Hi, I just came to post a little problem with the icon that is missing. By the way, thank you very much for the theme, I really loved it.
![Captura de tela de 2022-10-13 09-13-12](https://user-images.githubusercontent.com/113995667/195593118-eed267b3-7a46-48ba-8cc6-4063340e72e1.png)
Privacy > Location Services
![Captura de tela de 2022-10-13 09-13-20](https://user-images.githubusercontent.com/113995667/195593281-69788edc-1b43-4867-b70a-a1947d0a5e3a.png)

Again, I would like to thank you for the work on your theme, really one of the most beautiful and perfect I've ever seen :)

**Comment by Fausto-Korpsvart** [comment]
> [XMelph](/XMelph)

Hello, @XMelph

That's a problem with the icon package not being adapted to the changes that have been made in GNOME; unfortunately, I don't maintain the icon project because I don't know very well how the structure of an icon package works. You can try a more up-to-date icon package.
I intend to get involved in icons to create a package, but due to lack of time I haven't done it yet, so I can't promise to fix this bug, at least not in a short time, as I will try to get involved in icons when I have more time and information.

Sorry for not being helpful, and thank you for your support.

And by the way, the audio lines are correct.
