### ISSUE TITLE
GNOME 45 - Theme Supported?

### ISSUE THREAD

**Issue by D3vil0p3r** [Fausto-Korpsvart/Tokyo-Night-GTK-Theme#43]
Hello @Fausto-Korpsvart 
Your GTK-Themes will support GNOME 45 that should be released in September?

**Comment by Fausto-Korpsvart** [comment]
> Hello @Fausto-Korpsvart Your GTK-Themes will support GNOME 45 that should be released in September?

 Hello, @D3vil0p3r .

The changes to the Gnome 45 theme are great, aren't they?

Regarding your question, well, that's the intention, to be able to support Gnome 45 and those to come, the problem, as always, is that my work doesn't leave me much time to advance as I would like, in fact I have installed a Beta version of Fedora 39 to see the changes, although the adaptation of my themes will also depend on the original theme creator because I'm still learning how GTK themes work.

I'm already working on modifying the `Jasper` theme from source code in SASS, with the installer and the versions that come in `Jasper`; the main `Tokyonight` theme is already working, now I have to add the `Moon`, `Storm` versions and fix some problems in the `Light` theme, but unfortunately I'm not making progress as I would like, I wish I could dedicate more time but I can only dedicate part of my free time because I also need to rest.

But I am making progress and with the GNOME update coming up, I have started to check the changes to try to adapt it myself but, as I said before, it also depends on the theme creator for those things I still don't understand about GTK themes.

But yes, I will also try to support Gnome 45.

**Comment by eldskald** [comment]
I just installed the Tokyonight Dark B on Gnome 45. Almost everything seems right, here is what I think is wrong:

![image](https://github.com/Fausto-Korpsvart/Tokyo-Night-GTK-Theme/assets/49042948/12ac4610-a8ea-4bf1-9af0-24637e240dbf)

That left panel seems to be the same color as before, gray.

![image](https://github.com/Fausto-Korpsvart/Tokyo-Night-GTK-Theme/assets/49042948/1db240c9-7ea3-4564-853b-3c79fac2b30d)

Same color shows up on Nautilus. It also shows up on the widgets on the top bar, as well as the calendar but I can't screenshot them for some reason. Actually, the windows these widgets spawn seem completely unchanged.

One last bonus:

![image](https://github.com/Fausto-Korpsvart/Tokyo-Night-GTK-Theme/assets/49042948/e60dc996-5721-4337-810b-7e6933bcb31a)

![image](https://github.com/Fausto-Korpsvart/Tokyo-Night-GTK-Theme/assets/49042948/131dbe30-fa21-4fe4-9765-8ab91a6c1043)

Top bar doesn't change on Alacritty, but it does change on Gnome Console. Maybe alacritty isn't using GTK but then how is its top bar the same as everything else before applying the theme? I don't understand GTK or Gnome, maybe it isn't the theme's job to do this whence why I put this as a bonus.

**Comment by Fausto-Korpsvart** [comment]
This is what it looks like in Fedora 39 and Gnome 45, with a new darker version of Tokyonight in testing; but I still have some details to work out before upgrading.

![Tokyonight-F39-G45](https://github.com/Fausto-Korpsvart/Tokyo-Night-GTK-Theme/assets/47998118/7ba6a859-7148-4935-ba75-7fddee19a2d7)

**Comment by D3vil0p3r** [comment]
Thank you @Fausto-Korpsvart I'm here just to say I have the same "issue" explained by @eldskald

**Comment by Fausto-Korpsvart** [comment]
> Thank you @Fausto-Korpsvart I'm here just to say I have the same "issue" explained by @eldskald 
> 
> These updates will be applied also to other themes like NightFox, Gruvbox and so on?

Of course, after updating the Tokyonight theme, I will continue with all the other themes.
Currently I just need to finish some of the assets and small details that I want to get ready.

 Again, I know this is taking a while, but I'm still working on it, thanks for the wait and patience };-]

**Comment by D3vil0p3r** [comment]
We thank you so much for your work!

**Comment by wojciech-zurek** [comment]
@Fausto-Korpsvart Can you share a theme on another branch for testing purposes (even if it is not ready yet)?

**Comment by D3vil0p3r** [comment]
Hello @Fausto-Korpsvart 
is there a release date for this issue fix?

**Comment by Fausto-Korpsvart** [comment]
> Hello @Fausto-Korpsvart is there a release date for this issue fix?

Sorry for the delay, you can try this version, but I still want to fix some details and then upload the source code update.

[Tokyonight-Testing](https://github.com/Fausto-Korpsvart/Tokyo-Night-GTK-Theme/issues/49#issuecomment-1862883935)

**Comment by D3vil0p3r** [comment]
Thank you.

**Comment by D3vil0p3r** [comment]
> > Hello @Fausto-Korpsvart is there a release date for this issue fix?
> 
> Sorry for the delay, you can try this version, but I still want to fix some details and then upload the source code update.
> 
> [Tokyonight-Testing](https://github.com/Fausto-Korpsvart/Tokyo-Night-GTK-Theme/issues/49#issuecomment-1862883935)

I tried it but I'm still getting this issueon having that gray color on left part of the window

![image](https://github.com/Fausto-Korpsvart/Tokyo-Night-GTK-Theme/assets/83867734/cee386c2-08ea-436d-9d9a-8ba045458e2b)

**Comment by Fausto-Korpsvart** [comment]
> > > Hello @Fausto-Korpsvart is there a release date for this issue fix?
> > 
> > 
> > Sorry for the delay, you can try this version, but I still want to fix some details and then upload the source code update.
> > [Tokyonight-Testing](https://github.com/Fausto-Korpsvart/Tokyo-Night-GTK-Theme/issues/49#issuecomment-1862883935)
> 
> I tried it but I'm still getting this issueon having that gray color on left part of the window
> 
> ![image](https://private-user-images.githubusercontent.com/83867734/293194520-cee386c2-08ea-436d-9d9a-8ba045458e2b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDM4NTc2MTYsIm5iZiI6MTcwMzg1NzMxNiwicGF0aCI6Ii84Mzg2NzczNC8yOTMxOTQ1MjAtY2VlMzg2YzItMDhlYS00MzZkLTlkOWEtOGJhMDQ1NDU4ZTJiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI5VDEzNDE1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI0YjUyNjZjYTA4YzIwZGQ1ODljOTFjY2NmZTBjY2U1ZGRjMTg5ZmE5NDM4Y2ZhODRkODAxZWZiOGI4YjE4ZTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sViW_otZb_Ka5kQO_8h-g__HOnyxuyv8flduF8m65r4)

Which version of Gnome are you using?, I would also like to know which distro you are using?, because it is very rare that this happens, I have the latest version of Gnome on Fedora and I have tried on several distro's with Gnome and I don't have this problem.

**Comment by D3vil0p3r** [comment]
Hey @Fausto-Korpsvart I'm using latest GNOME version and I'm using Arch Linux (I'm using it in a VMware VM).

**Comment by D3vil0p3r** [comment]
I will investigate deeply in that and I will keep you updated.

**Comment by D3vil0p3r** [comment]
Very strange. I just upgraded my pure Arch Linux Virtual Machine and I cloned your repository and moved a theme in the theme folder like:
```
git clone https://github.com/Fausto-Korpsvart/Tokyo-Night-GTK-Theme
cd Tokyo-Night-GTK-Theme/themes
sudo cp -rf Tokyonight-Dark-B /usr/share/themes/
ln -s /usr/share/themes/Tokyonight-Dark-B/gtk-4.0/assets ~/.config/gtk-4.0/assets
ln -s /usr/share/themes/Tokyonight-Dark-B/gtk-4.0/gtk.css ~/.config/gtk-4.0/gtk.css
ln -s /usr/share/themes/Tokyonight-Dark-B/gtk-4.0/gtk-dark.css ~/.config/gtk-4.0/gtk-dark.css
```
Then, I move to Settings -> Appearance -> setting dark theme, finally I go to Tweaks, and set Legacy Applications as "TokyoNight-Dark-B" and reboot.
And I still get:
![image](https://github.com/Fausto-Korpsvart/Tokyo-Night-GTK-Theme/assets/83867734/c02be398-c2ae-4336-80ca-f9ce0f002e7a)

Am I missing something during the implementation of the theme? What are the steps you do to install it?

**Comment by Fausto-Korpsvart** [comment]
> Very strange @Fausto-Korpsvart . I just upgraded my pure Arch Linux Virtual Machine and I cloned your repository and moved a theme in the theme folder like:
> 
> ```
> git clone https://github.com/Fausto-Korpsvart/Tokyo-Night-GTK-Theme
> cd Tokyo-Night-GTK-Theme/themes
> sudo cp -rf Tokyonight-Dark-B /usr/share/themes/
> ln -s /usr/share/themes/Tokyonight-Dark-B/gtk-4.0/assets ~/.config/gtk-4.0/assets
> ln -s /usr/share/themes/Tokyonight-Dark-B/gtk-4.0/gtk.css ~/.config/gtk-4.0/gtk.css
> ln -s /usr/share/themes/Tokyonight-Dark-B/gtk-4.0/gtk-dark.css ~/.config/gtk-4.0/gtk-dark.css
> ```
> 
> Then, I move to Settings -> Appearance -> setting dark theme, finally I go to Tweaks, and set Legacy Applications as "TokyoNight-Dark-B" and reboot. And I still get: ![image](https://private-user-images.githubusercontent.com/83867734/295359621-c02be398-c2ae-4336-80ca-f9ce0f002e7a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ5MDY1NTYsIm5iZiI6MTcwNDkwNjI1NiwicGF0aCI6Ii84Mzg2NzczNC8yOTUzNTk2MjEtYzAyYmUzOTgtYzJhZS00MzM2LTgwY2EtZjljZTBmMDAyZTdhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEwVDE3MDQxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE5MDNkMTQ1OTdjMzhhMDgxYjMxZmRhN2NkYWUyODczNjJjMWYyNTdiOGUzOTk0NzljYzY2NWI5Mjg5N2Y4NjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qfMaTEBIhlz1u76qM8f0LXdw2ZYPmFhAGZwHip8vVXA)
> 
> Am I missing something during the implementation of the theme? What are the steps you do to install it?
> 
> Are you working in Wayland or Xorg?

Greetings, @D3vil0p3r 

I'm using Gnome Boxes and Wayland.

Well, I always do the standard Arch Linux installation,
but this time I found `Calam Arch Installer`, I guess you already know it, anyway, from what you have done, the only different thing I do, is that I put the themes in `.themes` in `$HOME`.

I'm going to try putting the themes in `usr/share/themes` to see if this is what affects it and, if so, see how to fix it, because I do what we all do to install a distro and the themes in Gnome.

It is always also necessary to install the `gtk-engine-murrine` package, as it says in the description, but even without installing that package the theme doesn't give me an error; as I said before, then I will test placing the themes in `/usr/share/themes` to find out if this is what affects and find a way to fix it.

Thanks for reporting.

**Comment by D3vil0p3r** [comment]
@Fausto-Korpsvart thank you for the answer. I had already `gtk-engine-murrine`. Furthermore, I tried to use `.themes` directory in `$HOME` but I get the same effect. I don't know if other users are getting the same result.

**Comment by D3vil0p3r** [comment]
Hello @Fausto-Korpsvart Did you have the chance to give a deeper look to it?

**Comment by Fausto-Korpsvart** [comment]
> Hello @Fausto-Korpsvart Did you have the chance to give a deeper look to it?

Greetings, @D3vil0p3r.

I've been testing and in Gnome I'm not having any problems, where I found some small problems was in XFCE.

I've thought a lot about changing the base theme from Jasper to Magnetic, I think this theme is better adapted to the changes introduced by Gnome 45, I've already done some tests with several base themes and I like the Magnetic theme better.
I've already started to work a bit on it, and soon I'll have more time to dedicate completely to the project that I've had a bit abandoned.

Thanks for waiting so long and for the support.

This is the last version I worked on, maybe you could try it and see if the bug persists, anyway I'm already working on migrating to Magnetic as a base theme.
[Tokyionight-Themes-Updated](https://github.com/Fausto-Korpsvart/Tokyo-Night-GTK-Theme/files/14085937/Tokyionight-Themes.zip)

**Comment by D3vil0p3r** [comment]
Thank you very much @Fausto-Korpsvart ! I switched from Arch Linux to NixOS. I tried again your GTK themes, and they seem to work correctly in NixOS... so maybe on a clean Arch Linux there could be a missing dependency to install (apart gtk-murrine).

When you will switch to Magnetic and you will officially release the new versions, I will push them to Nix repository.

**Comment by eldskald** [comment]
![image](https://github.com/Fausto-Korpsvart/Tokyo-Night-GTK-Theme/assets/49042948/687d9861-9f3b-4b1d-a1fb-df2b03a937ef)

Now they're breaking on my system this time, hahaha, also Arch. Previous one worked great. I managed to fix it by simply applying the gtk-4.0 from the previous link you provided (the Tokyonight-Testing one) with everything else from this new one. It all just works.

Other things I noticed:
- The legacy buttons version didn't had legacy buttons on all non Gnome applications, like the kitty terminal and spotify. Browser was fine though.
- When you swap workspaces, an indicator on the bottom of the screen shows up, right? This indicator has no background, it's just the white dots, which can blend with the wallpaper if it's too bright. I know Gnome default theme has a background for these dots, so I thought this one was supposed to have one too, is it intentional?
- Non Gnome apps (kitty and spotify) have the bottom corners slightly bugged. It's like they have a 1 pixel border that you can see curving at the corners, like they have corner radius but the contents of the window do not have the corner radius, so you can see just the 1px border curving behind the contents. Browser and all other apps are fine, the ones like Nautilus, Settings and Gnome Tweaks all have corner radii with everything working, meanwhile the browser has no corner radii but the 1px border also doesn't. It only happens on the contents of the window, the top bar of the window (the one with the title and buttons) doesn't have this problem on no app at all.

**Comment by Fausto-Korpsvart** [comment]
Greetings and thanks for the report, @eldskald 

Regarding the things you noticed

- I find it strange that Arch has so many problems, as I have tested it with the Calam Arch Installer ISO, with Manjaro and the standard version of Arch in Gnome Boxes and I have not seen these problems, except Kitty, as I use it without windows decoration, but Spotify, Github Desktop and other apps that are not native to Gnome, work correctly.
Anyway, I'll do more tests to find out what's wrong with Arch Linux that causes so many problems with the themes and try to solve them with the new base theme change from Jasper to Magnetic.

- Some parts of the base theme I haven't modified, so the desktop swap points have the base theme styles,
so I will check how to return the default GNOME theme styles to return the background.

- The rounded bottom corners problem comes from a long time ago, as far as I understand, this is because in GTK3 they had not implemented the rounded corners at the bottom, this was implemented in GTK4 with Libadwaita, so non GTK4 applications are limited to render with GTK3 and drag with the problems it brings.
I added that pixel to the decoration to match GTK4 styles, but now I'm considering removing it, as it has a lot of problems with several applications, and aesthetically it doesn't look good, even with Firefox, which in theory is already working with bottom corners, but even with that, the theme doesn't seem to work properly, so, with the change of base theme to Magnetic, maybe I'll leave these styles as they come from the theme so we don't face this problem, at least until I try to solve it in some other way.

Thanks for reporting, starting February, I will be able to dedicate more time to finally finish updating these projects, as it has taken me too long due to different circumstances, but I really appreciate the support and patience, thank you.

**Comment by D3vil0p3r** [comment]
> > Hello @Fausto-Korpsvart Did you have the chance to give a deeper look to it?
> 
> Greetings, @D3vil0p3r.
> 
> I've been testing and in Gnome I'm not having any problems, where I found some small problems was in XFCE.
> 
> I've thought a lot about changing the base theme from Jasper to Magnetic, I think this theme is better adapted to the changes introduced by Gnome 45, I've already done some tests with several base themes and I like the Magnetic theme better. I've already started to work a bit on it, and soon I'll have more time to dedicate completely to the project that I've had a bit abandoned.
> 
> Thanks for waiting so long and for the support.
> 
> This is the last version I worked on, maybe you could try it and see if the bug persists, anyway I'm already working on migrating to Magnetic as a base theme. [Tokyionight-Themes-Updated](https://github.com/Fausto-Korpsvart/Tokyo-Night-GTK-Theme/files/14085937/Tokyionight-Themes.zip)

Sorry for my late reply @Fausto-Korpsvart . Now I tested on Arch Linux. If I use this TokyoNight Themes Updated file, after linking the gtk-4.0 content (assets, gtk.css and gtk-dark.css (and maybe also the same for gtk-3.0), it seems to work correctly. Can you apply the same fix also on other your themes like Gruvbox and NightFox?

**Comment by Fausto-Korpsvart** [comment]
> > > Hello @Fausto-Korpsvart Did you have the chance to give a deeper look to it?
> > 
> > 
> > Greetings, @D3vil0p3r.
> > I've been testing and in Gnome I'm not having any problems, where I found some small problems was in XFCE.
> > I've thought a lot about changing the base theme from Jasper to Magnetic, I think this theme is better adapted to the changes introduced by Gnome 45, I've already done some tests with several base themes and I like the Magnetic theme better. I've already started to work a bit on it, and soon I'll have more time to dedicate completely to the project that I've had a bit abandoned.
> > Thanks for waiting so long and for the support.
> > This is the last version I worked on, maybe you could try it and see if the bug persists, anyway I'm already working on migrating to Magnetic as a base theme. [Tokyionight-Themes-Updated](https://github.com/Fausto-Korpsvart/Tokyo-Night-GTK-Theme/files/14085937/Tokyionight-Themes.zip)
> 
> Sorry for my late reply @Fausto-Korpsvart . Now I tested on Arch Linux. If I use this TokyoNight Themes Updated file, after linking the gtk-4.0 content (assets, gtk.css and gtk-dark.css (and maybe also the same for gtk-3.0), it seems to work correctly. Can you apply the same fix also on other your themes like Gruvbox and NightFox?

@D3vil0p3r, Finally I have updated the theme, you are free to try this new version that I will update with small corrections in the following days.

Gruvbox and Nightfox will be ready in the next few days, since I had a problem and due to an error I lost the assets of all the themes, so now I have to redo everything again, my intention was to update all the themes at once, but I will update the other themes as I finish the assets for each theme.

**Comment by D3vil0p3r** [comment]
@Fausto-Korpsvart thank you very much! When I go back home I will try it for sure! I hope to see the related updates also on the other themes! Thank you for your wonderful work!

**Comment by ahkdigital** [comment]
Suggestion: I think it would be cool if the calendar date and title backgrounds were the lighter purple (like the Today part where the events are shown): 

![Screenshot from 2024-04-29 14-28-45](https://github.com/Fausto-Korpsvart/Tokyo-Night-GTK-Theme/assets/95383159/4b96bcd9-21c3-432b-9460-62fa10b131f5)

**Comment by Fausto-Korpsvart** [comment]
> Suggestion: I think it would be cool if the calendar date and title backgrounds were the lighter purple (like the Today part where the events are shown) instead of grey.
> 
> This is actually Gnome 46 and I'm using the Tokyo-Dark-Storm theme, so let me know if I should move it:
> 
> ![Screenshot from 2024-04-29 14-28-45](https://private-user-images.githubusercontent.com/95383159/326547643-4b96bcd9-21c3-432b-9460-62fa10b131f5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ0MTgyNjcsIm5iZiI6MTcxNDQxNzk2NywicGF0aCI6Ii85NTM4MzE1OS8zMjY1NDc2NDMtNGI5NmJjZDktMjFjMy00MzJiLTk0NjAtNjJmYTEwYjEzMWY1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI5VDE5MTI0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIzZjIyMTVmMmI3M2IzYjA3ZWNjNGFkNTUyMjQ1NzRhNDcxZmQ3MDg2NmRhMTJhZTFmYTk2YTBlYjQwZDBjM2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-COfQqk-bAStSnCUpwz9EbvHJULB1mSUbZ1MRWKxovw)

Hello, @ahkdigital, Actually this is a bug that comes with the update to Gnome 46, but I have already fixed it, and soon I will make the update that fixes many bugs not only in Gnome Shell.

Thanks for the suggestion and report.

**Comment by Fausto-Korpsvart** [comment]
The theme has been updated, please test and report bugs };]

**Comment by Fausto-Korpsvart** [comment]
> What about Gruvbox, NightFox and the other themes about the last update @Fausto-Korpsvart ?

@D3vil0p3r, Since the Tokyonight theme has most of the Gnome 46 compatibility bugs fixed, I will start with the other themes; I am currently working on finishing adding the missing assets in Tokyonight, and then I will fully focus on the other themes, since TN is my base theme for the other themes, I want to fully finish TN and then give priority to the other themes.

I was working on Gruvbox before the Gnome upgrade from Gnome 45 to 46 and instead of fixing bugs in G45 I preferred to finish TN first and then focus on Gruvbox with the bugs fixed.

But don't worry, I'm working on it, work leaves me little time, but the other themes will also have their updates.

Thank you for your support };]

**Comment by ahkdigital** [comment]
> The theme has been updated, please test and report bugs };]

Calendar is looking good! Thank you!!

**Comment by D3vil0p3r** [comment]
Hello @Fausto-Korpsvart ^^ any news about the status of Tokyo Night and the other related themes?

**Comment by Fausto-Korpsvart** [comment]
> Hello @Fausto-Korpsvart ^^ any news about the status of Tokyo Night and the other related themes?

Yes, I hope to update Tokyonight and Gruvbox this week, I've been a little busy with work, but I'll try to update these two themes this week, then I'll continue updating little by little with the other themes }:-]

**Comment by Fausto-Korpsvart** [comment]
Gruvbox and Tokyonight, both themes updated, I hope you will test and report bugs.

Thank you for your support.

**Comment by D3vil0p3r** [comment]
> Gruvbox and Tokyonight, both themes updated, I hope you will test and report bugs.
> 
> Thank you for your support.

Thank you very much! I will test them. What about Nightfox?

**Comment by D3vil0p3r** [comment]
@Fausto-Korpsvart can you please rename `theme` directory to `themes` in order to keep the right naming convention?

**Comment by Fausto-Korpsvart** [comment]
> @Fausto-Korpsvart can you please rename `theme` directory to `themes` in order to keep the right naming convention?

Done!
