### ISSUE TITLE
Suggestion: reduce the Radiuses

### ISSUE THREAD

**Issue by manticore-projects** [Fausto-Korpsvart/Tokyo-Night-GTK-Theme#57]
Greetings!

First of all, big shout-out  for marrying the palette with the Magnetic GTK Theme!
Although for my taste, everything is way too round now due to @vinceliuice preference.

So below are my suggestions for more toned down appearance:

Tokyo-Night-GTK-Theme/theme/src/sass/_variables.scss
```css
// Radiuses
$window-radius: 6px;
$modal-radius: 2px;
$corner-radius: 6px;
$menu-radius: $corner-radius;
$menuitem-radius: $menu-radius;
$circular-radius: 6px;
```

Tokyo-Night-GTK-Theme/theme/src/sass/_tweaks.scss
```css
// Windows outline style
$outline: 'true';
```

![image](https://github.com/Fausto-Korpsvart/Tokyo-Night-GTK-Theme/assets/18080123/2a2138f7-74de-49c5-861d-8b32e80ac2ab)

**Comment by manticore-projects** [comment]
If this finds some interest I would submit a PR to introduce a `factor` variable for controlling the rounding. I would also fix the `outline` variable which is not set correctly from the build script (for Moon Dark B-LB at least).

**Comment by Fausto-Korpsvart** [comment]
Hello, @manticore-projects.

Actually, I had already thought to put the option to choose a less rounded theme when installing, for those of us who use a Window Manager.

> fix the outline variable which is not set correctly from the build script (for Moon Dark B-LB at least).

About the Outline variable fix, I don't quite understand what you mean, when I install Moon Dark B-LB I get the theme correctly; could you explain a bit more, please?

A screenshot of the Moon Dark Border Legacy Buttons theme, everything works in the GTK theme and in the Shell with the outline version.

![Moon-Dark-B-LB](https://github.com/Fausto-Korpsvart/Tokyo-Night-GTK-Theme/assets/47998118/8a1f2cf5-3501-481f-a2c0-6437cd75c434)

> // Windows outline style 
> $outline: 'true';

By the way, in the `_tweaks.scss file`, I purposely set the `outline` value to `false` so that a more standard theme is installed by default, and if someone wants the outline theme they only have to choose the `outline` options for GTK and `float` for the Shell.

Thanks for the suggestion.
And of course any help is always welcome.

**Comment by manticore-projects** [comment]
Thank you for prompt feeback.

> About the Outline variable fix, I don't quite understand what you mean, when I install Moon Dark B-LB I get the theme correctly; could you explain a bit more, please?

When I take the old theme from Gnome-Looks everything is fine.
With the new theme from Gnome-Looks the Moon/Dark variant does not have the outline. There is another comment on Gnome-looks in this regard too. Interestingly the Light variants have that outline.

Downloading the source and setting the CSS variable fixed it for me.
