### ISSUE TITLE
Low contrast and black corners in LibreOffice with Tokyonight-Dark

### ISSUE THREAD

**Issue by Syphdias** [Fausto-Korpsvart/Tokyo-Night-GTK-Theme#60]
I noticed that LibreOffice is barely usable.

The buttons have very low contrast and the the selector is hardly noticeable.
There is also are black corner (not as essential to the usage though)

![image](https://github.com/Fausto-Korpsvart/Tokyo-Night-GTK-Theme/assets/16988672/dedfd805-bf26-4f55-9130-61e29808bea1)

Is there anything that can be done about it?

**Comment by Fausto-Korpsvart** [comment]
@Syphdias, the problem with the dark corners on the buttons has been fixed, but I haven't updated yet because there are still some changes I want to make before updating.

Regarding the icons, this can be fixed from LibreOffice, just press `Alt + F12`, in the next window go to: `LibreOffce` `View` and there you can change the style of the icons; I leave a screenshot as a sample.

![LibreOffice](https://github.com/Fausto-Korpsvart/Tokyo-Night-GTK-Theme/assets/47998118/b5bfc694-2177-4699-b9e0-ca0be40a0d98)

I will update soon to fix the dark corners on the buttons.

Thank you for reporting the error.

**Comment by Syphdias** [comment]
Thank you very much!

So, LibreOffice does not change its icon theme depending on if it is a light or dark issue it seems. Weird choice, or a bug. In my case it selected "Colibre" instead of "Colibre (dark)". (Side note: SVG versions are not as sharp and seem blurry – huh?!)

**Comment by Fausto-Korpsvart** [comment]
> Thank you very much!
> 
> So, LibreOffice does not change its icon theme depending on if it is a light or dark issue it seems. Weird choice, or a bug. In my case it selected "Colibre" instead of "Colibre (dark)". (Side note: SVG versions are not as sharp and seem blurry – huh?!)

I also find it strange that the theme and icons do not change depending on the system theme.

And well, I've already updated it so that the toolbar matches the general colour of the theme and looks a bit more uniform.

And you're right, for SVG icons they don't look very good, those are the problems that GTK4 is supposed to fix, but LibreOffice hasn't migrated to GTK4 and GTK3 doesn't help much with these kinds of problems.

Again, thanks for reporting the problem and I hope you enjoy the theme, any bugs you find feel free to report them.
