### ISSUE TITLE
An idea for your next/another theme

### ISSUE THREAD

**Issue by damir78** [Fausto-Korpsvart/Tokyo-Night-GTK-Theme#8]
Hello @Fausto-Korpsvart 

i'm impressed by your themes https://www.gnome-look.org/. Can I suggest an idea for your next/another theme? :)

![image](https://user-images.githubusercontent.com/12588674/168503301-5c69c27e-ce24-45c0-a3a6-672bf60089fe.png)

Yellow fonts on dark-grey-blue. If you find it interesting - it will be Nr1 :)

Thanks

**Comment by Fausto-Korpsvart** [comment]
> Hello @Fausto-Korpsvart
> 
> i'm impressed by your themes https://www.gnome-look.org/. Can I suggest an idea for your next/another theme? :)
> 
> ![image](https://user-images.githubusercontent.com/12588674/168503301-5c69c27e-ce24-45c0-a3a6-672bf60089fe.png)
> 
> Yellow fonts on dark-grey-blue. If you find it interesting - it will be Nr1 :)
> 
> Thanks

Hello, @damir78, I will check the colour palette you propose and see how it looks, but for the moment I won't promise anything, because I have to update most of the themes to work with 'Gnome 42' version and this takes a bit of time because I have to check details to make everything work well, but I will take it into consideration and I will test to see how this colour palette looks like, thanks for your support and suggestion. };-]
